"use client";

import { createContext, type ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type LanguageCode = "EN" | "HI" | "BN";

const translations: Record<Exclude<LanguageCode, "EN">, Record<string, string>> = {
  HI: {
    "Cyber Scam Awareness": "साइबर ठगी जागरूकता",
    "Learn & protect": "जानें और सुरक्षित रहें",
    "Experience Scam": "ठगी का अनुभव करें",
    "Scam simulator": "ठगी सिम्युलेटर",
    "(Scam Simulator)": "(ठगी सिम्युलेटर)",
    "AI Scam Analyzer": "एआई ठगी विश्लेषक",
    "I Have Been Scammed": "मेरे साथ ठगी हुई है",
    "Get help & report": "मदद लें और रिपोर्ट करें",
    "(Report a Scam)": "(ठगी की रिपोर्ट करें)",
    "Financial cyber fraud?": "वित्तीय साइबर ठगी?",
    "Call 1930": "1930 पर कॉल करें",
    "Think before you click": "क्लिक करने से पहले सोचें",
    "Don’t open unknown links.": "अनजान लिंक न खोलें।",
    "Verify before you trust": "भरोसा करने से पहले जाँचें",
    "Use official channels.": "आधिकारिक माध्यमों का उपयोग करें।",
    "Protect your information": "अपनी जानकारी सुरक्षित रखें",
    "Never share OTP, PIN or CVV.": "OTP, PIN या CVV कभी साझा न करें।",
    "Know the signs. Stop the scam.": "संकेत पहचानें। ठगी रोकें।",
    "Learn how common scams work, recognise warning signs, and build everyday habits that protect you and your family.": "जानें कि सामान्य ठगी कैसे काम करती है, चेतावनी संकेत पहचानें और अपने परिवार को सुरक्षित रखने वाली आदतें बनाएँ।",
    "Try a safe simulation": "सुरक्षित अभ्यास करें",
    "Pause. Check. Protect.": "रुकें। जाँचें। सुरक्षित रहें।",
    "A few seconds of verification can prevent financial loss.": "कुछ सेकंड की जाँच आर्थिक नुकसान रोक सकती है।",
    "Explore common threats": "सामान्य खतरों को जानें",
    "Top scam categories": "मुख्य ठगी श्रेणियाँ",
    "Tap a category to learn its warning signs": "चेतावनी संकेत जानने के लिए श्रेणी चुनें",
    "Remember": "याद रखें",
    "Think before you click. Verify before you trust. Report suspicious activity to protect yourself and others.": "क्लिक से पहले सोचें, भरोसे से पहले जाँचें और संदिग्ध गतिविधि की रिपोर्ट करें।",
    "SAFE DIGITAL INDIA": "सुरक्षित डिजिटल भारत",
    "Stay Informed.": "जानकारी रखें।",
    "Welcome to Cyber Suraksha": "साइबर सुरक्षा में आपका स्वागत है",
    "Stay Secure.": "सुरक्षित रहें।",
    "Learn about common cyber scams, how to identify them, and what you can do to protect yourself and others.": "सामान्य साइबर ठगी, उनकी पहचान और स्वयं व दूसरों की सुरक्षा के तरीके जानें।",
    "Financial Fraud?": "वित्तीय ठगी?",
    "Helpline for cyber financial fraud": "साइबर वित्तीय ठगी हेल्पलाइन",
    "Learn about the latest scams, warning signs, and safe practices to protect yourself.": "नई ठगी, चेतावनी संकेत और स्वयं को सुरक्षित रखने के तरीके जानें।",
    "Explore Awareness": "जागरूकता देखें",
    "Learn about common cyber scams and stay protected.": "सामान्य साइबर ठगी के बारे में जानें और सुरक्षित रहें।",
    "Explore Scams": "ठगी के प्रकार देखें",
    "View All": "सभी देखें",
    "Courier / Customs Scam": "कूरियर / कस्टम ठगी",
    "Sextortion": "सेक्सटॉर्शन",
    "Social Media Impersonation": "सोशल मीडिया पहचान की नकल",
    "Matrimonial Scam": "वैवाहिक ठगी",
    "SIM / KYC Scam": "SIM / KYC ठगी",
    "Phishing": "फ़िशिंग",
    "Scam awareness guide": "ठगी जागरूकता मार्गदर्शिका",
    "A common example": "एक सामान्य उदाहरण",
    "How this scam happens": "यह ठगी कैसे होती है",
    "Warning signs": "चेतावनी संकेत",
    "Protect yourself": "अपनी सुरक्षा करें",
    "Lost money or shared sensitive information?": "क्या पैसे गए या संवेदनशील जानकारी साझा हुई?",
    "Act quickly. Contact your bank, save the evidence, and report the incident.": "जल्दी कार्रवाई करें। बैंक से संपर्क करें, सबूत बचाएँ और घटना की रिपोर्ट करें।",
    "Report online": "ऑनलाइन रिपोर्ट करें",
    "Experience Scam (Scam Simulator)": "ठगी का अनुभव (ठगी सिम्युलेटर)",
    "Step into real-life scam scenarios and learn how to make the right choices.": "वास्तविक जैसी ठगी परिस्थितियों में सही निर्णय लेना सीखें।",
    "Start Simulator": "सिम्युलेटर शुरू करें",
    "Scam Analyzer": "ठगी विश्लेषक",
    "Analyze suspicious messages, links, or content and check if they look like a scam.": "संदिग्ध संदेश, लिंक या सामग्री का विश्लेषण करके ठगी की जाँच करें।",
    "Analyze Now": "अभी विश्लेषण करें",
    "Help & Resources": "सहायता और संसाधन",
    "Report a scam": "ठगी की रिपोर्ट करें",
    "Find helpline numbers, reporting links, guidelines and useful resources.": "हेल्पलाइन नंबर, रिपोर्टिंग लिंक, दिशानिर्देश और उपयोगी संसाधन पाएँ।",
    "View Resources": "संसाधन देखें",
    "Remember: Think before you click. Verify before you trust. Report to protect.": "याद रखें: क्लिक से पहले सोचें। भरोसे से पहले जाँचें। सुरक्षा के लिए रिपोर्ट करें।",
    "Know More Tips": "और सुझाव जानें",
    "Digital Arrest": "डिजिटल अरेस्ट",
    "Fake police pressure": "नकली पुलिस का दबाव",
    "UPI Collect Request": "UPI कलेक्ट अनुरोध",
    "Unexpected payment": "अनपेक्षित भुगतान",
    "QR Code Scam": "QR कोड ठगी",
    "Scan-to-receive trick": "पैसे पाने के नाम पर स्कैन",
    "OTP Scam": "OTP ठगी",
    "Code theft": "कोड की चोरी",
    "Fake Investment": "नकली निवेश",
    "Guaranteed returns": "गारंटीड रिटर्न का झाँसा",
    "Fake Job": "नकली नौकरी",
    "Pay before joining": "ज्वाइनिंग से पहले भुगतान",
    "Courier Scam": "कूरियर ठगी",
    "Parcel threat": "पार्सल के नाम पर धमकी",
    "Loan App Scam": "लोन ऐप ठगी",
    "Predatory lending": "शोषणकारी ऋण",
    "Practise safely. Learn what a scam feels like before it happens.": "सुरक्षित अभ्यास करें और ठगी होने से पहले उसके संकेत पहचानें।",
    "Choose scenario": "परिस्थिति चुनें",
    "Spot the signs": "संकेत पहचानें",
    "See your result": "परिणाम देखें",
    "Track progress": "प्रगति देखें",
    "Choose a scenario": "परिस्थिति चुनें",
    "Start scenario": "अभ्यास शुरू करें",
    "WhatsApp message": "व्हाट्सऐप संदेश",
    "Cyber Crime Department:": "साइबर अपराध विभाग:",
    "Your Aadhaar is linked to an illegal parcel. Verify immediately to avoid arrest.": "आपका आधार एक अवैध पार्सल से जुड़ा है। गिरफ्तारी से बचने के लिए तुरंत सत्यापन करें।",
    "What would you do?": "आप क्या करेंगे?",
    "Open the link": "लिंक खोलें",
    "Call the number in the message": "संदेश में दिए नंबर पर कॉल करें",
    "Verify through an official government website": "आधिकारिक सरकारी वेबसाइट से जाँचें",
    "Check my answer": "मेरा उत्तर जाँचें",
    "Your result": "आपका परिणाम",
    "Good catch!": "बहुत बढ़िया!",
    "Never act on threats from an unknown caller. Verify independently.": "अनजान कॉलर की धमकी पर कार्रवाई न करें। स्वतंत्र रूप से जाँचें।",
    "Urgency and fear": "जल्दबाजी और डर",
    "Unknown link": "अनजान लिंक",
    "Unverified authority": "असत्यापित अधिकारी",
    "View my progress": "मेरी प्रगति देखें",
    "Your progress": "आपकी प्रगति",
    "Cyber Defender": "साइबर रक्षक",
    "Scenarios completed": "पूरे किए अभ्यास",
    "Try another scenario": "दूसरा अभ्यास करें",
    "Open full simulator": "पूरा सिम्युलेटर खोलें",
    "A safe place to make mistakes": "गलतियों से सुरक्षित रूप से सीखें",
    "This interactive journey uses realistic messages but never asks for passwords, OTPs, PINs or payment details.": "यह अभ्यास वास्तविक जैसे संदेश दिखाता है, लेकिन पासवर्ड, OTP, PIN या भुगतान विवरण कभी नहीं माँगता।",
    "Recognise pressure tactics": "दबाव की रणनीति पहचानें",
    "Practise safe verification": "सुरक्षित जाँच का अभ्यास करें",
    "Build confidence one scenario at a time": "हर अभ्यास के साथ आत्मविश्वास बढ़ाएँ",
    "Paste a suspicious message or link and understand the risk in seconds.": "संदिग्ध संदेश या लिंक डालें और कुछ सेकंड में जोखिम समझें।",
    "Upload or paste": "अपलोड या पेस्ट करें",
    "Analysis result": "विश्लेषण परिणाम",
    "Recommended actions": "सुझाए गए कदम",
    "Check suspicious content": "संदिग्ध सामग्री जाँचें",
    "Text": "टेक्स्ट",
    "Upload": "अपलोड",
    "Paste the suspicious message, email or URL here…": "संदिग्ध संदेश, ईमेल या URL यहाँ पेस्ट करें…",
    "We do not store what you paste here.": "आपकी सामग्री यहाँ संग्रहित नहीं की जाती।",
    "Analyze now": "अभी विश्लेषण करें",
    "High risk": "उच्च जोखिम",
    "Likely impersonation scam": "संभावित पहचान प्रतिरूपण ठगी",
    "The message uses urgency, authority and a request to act outside official channels.": "संदेश जल्दबाजी, अधिकार और गैर-आधिकारिक माध्यम से कार्रवाई का दबाव बनाता है।",
    "Warning signs detected": "चेतावनी संकेत मिले",
    "Threat of arrest or loss": "गिरफ्तारी या नुकसान की धमकी",
    "Urgent payment request": "तुरंत भुगतान की माँग",
    "Unknown phone number": "अनजान फोन नंबर",
    "Suspicious external link": "संदिग्ध बाहरी लिंक",
    "What should I do?": "मुझे क्या करना चाहिए?",
    "Stop communicating immediately": "तुरंत बातचीत बंद करें",
    "Do not transfer money or share details": "पैसे या निजी जानकारी साझा न करें",
    "Save screenshots and preserve evidence": "स्क्रीनशॉट और सबूत सुरक्षित रखें",
    "Report financial fraud on 1930": "वित्तीय ठगी की सूचना 1930 पर दें",
    "File a complaint on the official portal": "आधिकारिक पोर्टल पर शिकायत दर्ज करें",
    "Analyze another message": "दूसरा संदेश जाँचें",
    "Understand before you act": "कार्रवाई से पहले समझें",
    "The analyzer explains suspicious patterns in plain language so you can make a calmer, informed decision.": "विश्लेषक संदिग्ध पैटर्न सरल भाषा में समझाता है ताकि आप सोच-समझकर निर्णय लें।",
    "SMS": "SMS",
    "Screenshot": "स्क्रीनशॉट",
    "Email": "ईमेल",
    "QR code": "QR कोड",
    "Act quickly, preserve evidence, and report the incident to the right authorities.": "जल्दी कार्रवाई करें, सबूत बचाएँ और सही अधिकारियों को घटना की रिपोर्ट करें।",
    "Money just left your account?": "क्या अभी आपके खाते से पैसे निकले हैं?",
    "Call 1930 immediately. Fast reporting can improve the chance of blocking a transaction.": "तुरंत 1930 पर कॉल करें। जल्दी रिपोर्ट करने से लेनदेन रोकने की संभावना बढ़ती है।",
    "What happened?": "क्या हुआ?",
    "Act now": "अभी कार्रवाई करें",
    "Report & next steps": "रिपोर्ट और अगले कदम",
    "How did you lose money?": "पैसे कैसे गए?",
    "UPI": "UPI",
    "Bank transfer": "बैंक ट्रांसफर",
    "Debit / credit card": "डेबिट / क्रेडिट कार्ड",
    "E-wallet": "ई-वॉलेट",
    "Other": "अन्य",
    "Continue": "जारी रखें",
    "Financial fraud — act now": "वित्तीय ठगी — अभी कार्रवाई करें",
    "Call cybercrime helpline 1930": "साइबर अपराध हेल्पलाइन 1930 पर कॉल करें",
    "Contact your bank immediately": "तुरंत अपने बैंक से संपर्क करें",
    "Keep transaction ID, screenshots and phone numbers": "लेनदेन ID, स्क्रीनशॉट और फोन नंबर सुरक्षित रखें",
    "Next": "आगे",
    "National Cyber Crime Reporting Portal": "राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल",
    "Cybercrime helpline 1930": "साइबर अपराध हेल्पलाइन 1930",
    "Save evidence checklist": "सबूत सूची सहेजें",
    "Open incident data dashboard": "घटना डेटा डैशबोर्ड खोलें",
    "Authorized staff: view collected simulation and incident records.": "अधिकृत कर्मचारी: अभ्यास और घटना रिकॉर्ड देखें।",
    "You are not alone": "आप अकेले नहीं हैं",
    "Take one step at a time. Stop contact, call your bank, save evidence, then report through official channels.": "एक-एक कदम उठाएँ। संपर्क रोकें, बैंक को कॉल करें, सबूत बचाएँ और आधिकारिक माध्यम से रिपोर्ट करें।",
    "Your safety comes first": "आपकी सुरक्षा सबसे पहले",
    "Never confront a suspected scammer or travel to meet them.": "संदिग्ध ठग का सामना न करें और उससे मिलने न जाएँ।",
  },
  BN: {
    "Cyber Scam Awareness": "সাইবার প্রতারণা সচেতনতা",
    "Learn & protect": "জানুন ও নিরাপদ থাকুন",
    "Experience Scam": "প্রতারণার অভিজ্ঞতা নিন",
    "Scam simulator": "প্রতারণা সিমুলেটর",
    "(Scam Simulator)": "(প্রতারণা সিমুলেটর)",
    "AI Scam Analyzer": "এআই প্রতারণা বিশ্লেষক",
    "Check suspicious content": "সন্দেহজনক বিষয় যাচাই করুন",
    "I Have Been Scammed": "আমি প্রতারিত হয়েছি",
    "Get help & report": "সহায়তা নিন ও রিপোর্ট করুন",
    "(Report a Scam)": "(প্রতারণা রিপোর্ট করুন)",
    "Financial cyber fraud?": "আর্থিক সাইবার প্রতারণা?",
    "Call 1930": "১৯৩০ নম্বরে কল করুন",
    "Think before you click": "ক্লিক করার আগে ভাবুন",
    "Don’t open unknown links.": "অজানা লিঙ্ক খুলবেন না।",
    "Verify before you trust": "বিশ্বাসের আগে যাচাই করুন",
    "Use official channels.": "সরকারি মাধ্যম ব্যবহার করুন।",
    "Protect your information": "আপনার তথ্য সুরক্ষিত রাখুন",
    "Never share OTP, PIN or CVV.": "OTP, PIN বা CVV কখনও শেয়ার করবেন না।",
    "Know the signs. Stop the scam.": "লক্ষণ চিনুন। প্রতারণা রুখুন।",
    "Learn how common scams work, recognise warning signs, and build everyday habits that protect you and your family.": "সাধারণ প্রতারণা কীভাবে কাজ করে তা জানুন, সতর্কতার লক্ষণ চিনুন এবং নিজেকে ও পরিবারকে নিরাপদ রাখুন।",
    "Try a safe simulation": "নিরাপদ অনুশীলন করুন",
    "Pause. Check. Protect.": "থামুন। যাচাই করুন। সুরক্ষিত থাকুন।",
    "A few seconds of verification can prevent financial loss.": "কয়েক সেকেন্ডের যাচাই আর্থিক ক্ষতি ঠেকাতে পারে।",
    "Explore common threats": "সাধারণ ঝুঁকি জানুন",
    "Top scam categories": "প্রধান প্রতারণার ধরন",
    "Tap a category to learn its warning signs": "সতর্কতার লক্ষণ জানতে একটি ধরন বেছে নিন",
    "Remember": "মনে রাখুন",
    "Think before you click. Verify before you trust. Report suspicious activity to protect yourself and others.": "ক্লিকের আগে ভাবুন, বিশ্বাসের আগে যাচাই করুন এবং সন্দেহজনক কার্যকলাপ রিপোর্ট করুন।",
    "SAFE DIGITAL INDIA": "নিরাপদ ডিজিটাল ভারত",
    "Stay Informed.": "সচেতন থাকুন।",
    "Welcome to Cyber Suraksha": "সাইবার সুরক্ষায় আপনাকে স্বাগতম",
    "Stay Secure.": "নিরাপদ থাকুন।",
    "Learn about common cyber scams, how to identify them, and what you can do to protect yourself and others.": "সাধারণ সাইবার প্রতারণা, সেগুলি চেনার উপায় এবং নিজেকে ও অন্যদের সুরক্ষার পদ্ধতি জানুন।",
    "Financial Fraud?": "আর্থিক প্রতারণা?",
    "Helpline for cyber financial fraud": "সাইবার আর্থিক প্রতারণা হেল্পলাইন",
    "Learn about the latest scams, warning signs, and safe practices to protect yourself.": "নতুন প্রতারণা, সতর্কতার লক্ষণ এবং নিরাপদ থাকার অভ্যাস জানুন।",
    "Explore Awareness": "সচেতনতা দেখুন",
    "Learn about common cyber scams and stay protected.": "সাধারণ সাইবার প্রতারণা সম্পর্কে জানুন এবং নিরাপদ থাকুন।",
    "Explore Scams": "প্রতারণার ধরন দেখুন",
    "View All": "সব দেখুন",
    "Courier / Customs Scam": "কুরিয়ার / কাস্টমস প্রতারণা",
    "Sextortion": "সেক্সটরশন",
    "Social Media Impersonation": "সোশ্যাল মিডিয়া পরিচয় নকল",
    "Matrimonial Scam": "বিবাহ সংক্রান্ত প্রতারণা",
    "SIM / KYC Scam": "SIM / KYC প্রতারণা",
    "Phishing": "ফিশিং",
    "Scam awareness guide": "প্রতারণা সচেতনতা নির্দেশিকা",
    "A common example": "একটি সাধারণ উদাহরণ",
    "How this scam happens": "এই প্রতারণা যেভাবে ঘটে",
    "Warning signs": "সতর্কতার লক্ষণ",
    "Protect yourself": "নিজেকে সুরক্ষিত রাখুন",
    "Lost money or shared sensitive information?": "টাকা হারিয়েছেন বা সংবেদনশীল তথ্য দিয়েছেন?",
    "Act quickly. Contact your bank, save the evidence, and report the incident.": "দ্রুত ব্যবস্থা নিন। ব্যাংকে যোগাযোগ করুন, প্রমাণ রাখুন এবং ঘটনা রিপোর্ট করুন।",
    "Report online": "অনলাইনে রিপোর্ট করুন",
    "Experience Scam (Scam Simulator)": "প্রতারণার অভিজ্ঞতা (প্রতারণা সিমুলেটর)",
    "Step into real-life scam scenarios and learn how to make the right choices.": "বাস্তবসম্মত প্রতারণার পরিস্থিতিতে সঠিক সিদ্ধান্ত নিতে শিখুন।",
    "Start Simulator": "সিমুলেটর শুরু করুন",
    "Scam Analyzer": "প্রতারণা বিশ্লেষক",
    "Analyze suspicious messages, links, or content and check if they look like a scam.": "সন্দেহজনক বার্তা, লিঙ্ক বা বিষয় বিশ্লেষণ করে প্রতারণা কি না দেখুন।",
    "Analyze Now": "এখন বিশ্লেষণ করুন",
    "Help & Resources": "সহায়তা ও তথ্য",
    "Report a scam": "প্রতারণা রিপোর্ট করুন",
    "Find helpline numbers, reporting links, guidelines and useful resources.": "হেল্পলাইন নম্বর, রিপোর্টিং লিঙ্ক, নির্দেশিকা ও দরকারি তথ্য খুঁজুন।",
    "View Resources": "তথ্য দেখুন",
    "Remember: Think before you click. Verify before you trust. Report to protect.": "মনে রাখুন: ক্লিকের আগে ভাবুন। বিশ্বাসের আগে যাচাই করুন। সুরক্ষার জন্য রিপোর্ট করুন।",
    "Know More Tips": "আরও পরামর্শ জানুন",
    "Digital Arrest": "ডিজিটাল অ্যারেস্ট",
    "Fake police pressure": "ভুয়া পুলিশের চাপ",
    "UPI Collect Request": "UPI কালেক্ট অনুরোধ",
    "Unexpected payment": "অপ্রত্যাশিত পেমেন্ট",
    "QR Code Scam": "QR কোড প্রতারণা",
    "Scan-to-receive trick": "টাকা পাওয়ার নামে স্ক্যান",
    "OTP Scam": "OTP প্রতারণা",
    "Code theft": "কোড চুরি",
    "Fake Investment": "ভুয়া বিনিয়োগ",
    "Guaranteed returns": "নিশ্চিত লাভের প্রলোভন",
    "Fake Job": "ভুয়া চাকরি",
    "Pay before joining": "যোগদানের আগে টাকা",
    "Courier Scam": "কুরিয়ার প্রতারণা",
    "Parcel threat": "পার্সেলের নামে হুমকি",
    "Loan App Scam": "লোন অ্যাপ প্রতারণা",
    "Predatory lending": "শোষণমূলক ঋণ",
    "Practise safely. Learn what a scam feels like before it happens.": "নিরাপদে অনুশীলন করুন এবং প্রতারণার আগে তার লক্ষণ চিনুন।",
    "Choose scenario": "পরিস্থিতি বাছুন",
    "Spot the signs": "লক্ষণ চিনুন",
    "See your result": "ফলাফল দেখুন",
    "Track progress": "অগ্রগতি দেখুন",
    "Choose a scenario": "পরিস্থিতি বাছুন",
    "Start scenario": "অনুশীলন শুরু করুন",
    "WhatsApp message": "হোয়াটসঅ্যাপ বার্তা",
    "Cyber Crime Department:": "সাইবার অপরাধ বিভাগ:",
    "Your Aadhaar is linked to an illegal parcel. Verify immediately to avoid arrest.": "আপনার আধার একটি অবৈধ পার্সেলের সঙ্গে যুক্ত। গ্রেপ্তার এড়াতে এখনই যাচাই করুন।",
    "What would you do?": "আপনি কী করবেন?",
    "Open the link": "লিঙ্ক খুলব",
    "Call the number in the message": "বার্তার নম্বরে কল করব",
    "Verify through an official government website": "সরকারি ওয়েবসাইটে যাচাই করব",
    "Check my answer": "আমার উত্তর যাচাই করুন",
    "Your result": "আপনার ফলাফল",
    "Good catch!": "দারুণ ধরেছেন!",
    "Never act on threats from an unknown caller. Verify independently.": "অজানা কলারের হুমকিতে কাজ করবেন না। নিজে যাচাই করুন।",
    "Urgency and fear": "তাড়াহুড়ো ও ভয়",
    "Unknown link": "অজানা লিঙ্ক",
    "Unverified authority": "যাচাইহীন কর্তৃপক্ষ",
    "View my progress": "আমার অগ্রগতি দেখুন",
    "Your progress": "আপনার অগ্রগতি",
    "Cyber Defender": "সাইবার রক্ষক",
    "Scenarios completed": "সম্পন্ন অনুশীলন",
    "Try another scenario": "আরেকটি অনুশীলন করুন",
    "Open full simulator": "সম্পূর্ণ সিমুলেটর খুলুন",
    "A safe place to make mistakes": "নিরাপদে ভুল থেকে শেখার জায়গা",
    "This interactive journey uses realistic messages but never asks for passwords, OTPs, PINs or payment details.": "এই অনুশীলনে বাস্তবসম্মত বার্তা আছে, কিন্তু কখনও পাসওয়ার্ড, OTP, PIN বা পেমেন্ট তথ্য চায় না।",
    "Recognise pressure tactics": "চাপ দেওয়ার কৌশল চিনুন",
    "Practise safe verification": "নিরাপদ যাচাই অনুশীলন করুন",
    "Build confidence one scenario at a time": "প্রতিটি অনুশীলনে আত্মবিশ্বাস বাড়ান",
    "Paste a suspicious message or link and understand the risk in seconds.": "সন্দেহজনক বার্তা বা লিঙ্ক দিন এবং কয়েক সেকেন্ডে ঝুঁকি বুঝুন।",
    "Upload or paste": "আপলোড বা পেস্ট করুন",
    "Analysis result": "বিশ্লেষণের ফল",
    "Recommended actions": "প্রস্তাবিত পদক্ষেপ",
    "Text": "টেক্সট",
    "Upload": "আপলোড",
    "Paste the suspicious message, email or URL here…": "সন্দেহজনক বার্তা, ইমেইল বা URL এখানে পেস্ট করুন…",
    "We do not store what you paste here.": "আপনার দেওয়া তথ্য আমরা সংরক্ষণ করি না।",
    "Analyze now": "এখন বিশ্লেষণ করুন",
    "High risk": "উচ্চ ঝুঁকি",
    "Likely impersonation scam": "সম্ভাব্য পরিচয় নকল প্রতারণা",
    "The message uses urgency, authority and a request to act outside official channels.": "বার্তাটি তাড়াহুড়ো, কর্তৃত্ব এবং বেসরকারি মাধ্যমে কাজ করার চাপ তৈরি করে।",
    "Warning signs detected": "সতর্কতার লক্ষণ পাওয়া গেছে",
    "Threat of arrest or loss": "গ্রেপ্তার বা ক্ষতির হুমকি",
    "Urgent payment request": "জরুরি পেমেন্ট দাবি",
    "Unknown phone number": "অজানা ফোন নম্বর",
    "Suspicious external link": "সন্দেহজনক বাইরের লিঙ্ক",
    "What should I do?": "আমার কী করা উচিত?",
    "Stop communicating immediately": "এখনই যোগাযোগ বন্ধ করুন",
    "Do not transfer money or share details": "টাকা বা ব্যক্তিগত তথ্য দেবেন না",
    "Save screenshots and preserve evidence": "স্ক্রিনশট ও প্রমাণ সংরক্ষণ করুন",
    "Report financial fraud on 1930": "১৯৩০ নম্বরে আর্থিক প্রতারণা জানান",
    "File a complaint on the official portal": "সরকারি পোর্টালে অভিযোগ করুন",
    "Analyze another message": "আরেকটি বার্তা যাচাই করুন",
    "Understand before you act": "কাজের আগে বুঝুন",
    "The analyzer explains suspicious patterns in plain language so you can make a calmer, informed decision.": "বিশ্লেষক সহজ ভাষায় সন্দেহজনক ধরন বোঝায়, যাতে আপনি শান্তভাবে সিদ্ধান্ত নিতে পারেন।",
    "SMS": "SMS",
    "Screenshot": "স্ক্রিনশট",
    "Email": "ইমেইল",
    "QR code": "QR কোড",
    "Act quickly, preserve evidence, and report the incident to the right authorities.": "দ্রুত পদক্ষেপ নিন, প্রমাণ রাখুন এবং সঠিক কর্তৃপক্ষকে জানান।",
    "Money just left your account?": "এইমাত্র আপনার অ্যাকাউন্ট থেকে টাকা গেছে?",
    "Call 1930 immediately. Fast reporting can improve the chance of blocking a transaction.": "এখনই ১৯৩০ নম্বরে কল করুন। দ্রুত জানালে লেনদেন আটকানোর সম্ভাবনা বাড়ে।",
    "What happened?": "কী ঘটেছে?",
    "Act now": "এখনই ব্যবস্থা নিন",
    "Report & next steps": "রিপোর্ট ও পরবর্তী পদক্ষেপ",
    "How did you lose money?": "কীভাবে টাকা হারিয়েছেন?",
    "UPI": "UPI",
    "Bank transfer": "ব্যাংক ট্রান্সফার",
    "Debit / credit card": "ডেবিট / ক্রেডিট কার্ড",
    "E-wallet": "ই-ওয়ালেট",
    "Other": "অন্যান্য",
    "Continue": "চালিয়ে যান",
    "Financial fraud — act now": "আর্থিক প্রতারণা — এখনই ব্যবস্থা নিন",
    "Call cybercrime helpline 1930": "সাইবার অপরাধ হেল্পলাইন ১৯৩০-এ কল করুন",
    "Contact your bank immediately": "এখনই ব্যাংকের সঙ্গে যোগাযোগ করুন",
    "Keep transaction ID, screenshots and phone numbers": "লেনদেন ID, স্ক্রিনশট ও ফোন নম্বর রাখুন",
    "Next": "পরবর্তী",
    "National Cyber Crime Reporting Portal": "জাতীয় সাইবার অপরাধ রিপোর্টিং পোর্টাল",
    "Cybercrime helpline 1930": "সাইবার অপরাধ হেল্পলাইন ১৯৩০",
    "Save evidence checklist": "প্রমাণের তালিকা সংরক্ষণ করুন",
    "Open incident data dashboard": "ঘটনার ডেটা ড্যাশবোর্ড খুলুন",
    "Authorized staff: view collected simulation and incident records.": "অনুমোদিত কর্মী: অনুশীলন ও ঘটনার রেকর্ড দেখুন।",
    "You are not alone": "আপনি একা নন",
    "Take one step at a time. Stop contact, call your bank, save evidence, then report through official channels.": "এক ধাপ করে এগোন। যোগাযোগ বন্ধ করুন, ব্যাংকে কল করুন, প্রমাণ রাখুন এবং সরকারি মাধ্যমে রিপোর্ট করুন।",
    "Your safety comes first": "আপনার নিরাপত্তা সবার আগে",
    "Never confront a suspected scammer or travel to meet them.": "সন্দেহভাজন প্রতারকের মুখোমুখি হবেন না বা দেখা করতে যাবেন না।",
  },
};

interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function DashboardLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("EN");

  useEffect(() => {
    document.documentElement.lang = language === "HI" ? "hi" : language === "BN" ? "bn" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (text) => language === "EN" ? text : translations[language][text] ?? text,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useDashboardLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useDashboardLanguage must be used inside DashboardLanguageProvider");
  return context;
}
